version : "3.9"
services:
  backend:
    container_name: backend
    build:
      context: ../todo-tracker-api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  frontend:
    container_name: frontend
    build:
      context: ../todo-tracker-frontend
      dockerfile: Dockerfile
    ports:
     - "8080:8080"
    