version : "3.9"
services:
  backend:
    build:
      args:
        NODE_ENV: development
    volumes:
      - ../todo-tracker-api:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
  frontend:
    volumes:
      - ../todo-tracker-frontend:/app
      - /app/node_modules
    command: npm run serve
    